const data = [
    {
      id: 1,
      name: "Tokyo, Japan",
      description: "A 7-day trip to Tokyo, Japan. Visit the famous Shibuya Crossing, explore the vibrant Shinjuku district, and take a day trip to Hakone to see the beautiful Lake Ashi.",
      image: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8dG9reW98ZW58MHx8MHx8fDA%3D&w=1000&q=80",
      start_date: "2023-08-01",
      end_date: "2023-08-07",
      budget: 3000,
    },
    {
      id: 2,
      name: "Paris, France",
      description: "A 5-day trip to Paris, France. See the Eiffel Tower, visit the Louvre Museum, and take a boat ride down the Seine River.",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/La_Tour_Eiffel_vue_de_la_Tour_Saint-Jacques%2C_Paris_ao%C3%BBt_2014_%282%29.jpg/1200px-La_Tour_Eiffel_vue_de_la_Tour_Saint-Jacques%2C_Paris_ao%C3%BBt_2014_%282%29.jpg",
      start_date: "2023-08-15",
      end_date: "2023-08-19",
      budget: 2500,
    },
    {
      id: 3,
      name: "London, England",
      description: "A 4-day trip to London, England. See Big Ben, visit Buckingham Palace, and take a ride on the London Eye.",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqrq8VpS026HPs7bHyhTi4Yt3eh7lJXcjZfw&usqp=CAU",
      start_date: "2023-08-22",
      end_date: "2023-08-25",
      budget: 2000,
    },
    {
      id: 4,
      name: "Rome, Italy",
      description: "A 6-day trip to Rome, Italy. See the Colosseum, visit the Vatican City, and take a cooking class.",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqrq8VpS026HPs7bHyhTi4Yt3eh7lJXcjZfw&usqp=CAU",
      start_date: "2023-08-29",
      end_date: "2023-09-04",
      budget: 2500,
    },
    {
      id: 5,
      name: "Barcelona, Spain",
      description: "A 5-day trip to Barcelona, Spain. See the Sagrada Familia, visit the Picasso Museum, and take a walk along the beach.",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqrq8VpS026HPs7bHyhTi4Yt3eh7lJXcjZfw&usqp=CAU",
      start_date: "2023-09-07",
      end_date: "2023-09-11",
      budget: 2000,
    },
    {
      id: 6,
      name: "Amsterdam, Netherlands",
      description: "A 4-day trip to Amsterdam, Netherlands. See the Anne Frank House, visit the Van Gogh Museum, and take a boat ride through the canals.",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqrq8VpS026HPs7bHyhTi4Yt3eh7lJXcjZfw&usqp=CAU",
      start_date: "2023-09-14",
      end_date: "2023-09-17",
      budget: 1500,
    },
    {
      id: 7,
      name: "Dublin, Ireland",
      description: "A 3-day trip to Dublin, Ireland. See Trinity College, visit the Guinness Storehouse, and take a walk along the River Liffey.",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqrq8VpS026HPs7bHyhTi4Yt3eh7lJXcjZfw&usqp=CAU",
      start_date: "2023-09-18",
      end_date: "2023-09-20",
      budget: 1000,
    },
    {
      id: 8,
      name: "Lisbon, Portugal",
      description: "A 4-day trip to Lisbon, Portugal. See the Jerónimos Monastery, visit the São Jorge Castle, and take a ride on the Tram 28.",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqrq8VpS026HPs7bHyhTi4Yt3eh7lJXcjZfw&usqp=CAU",
      start_date: "2023-09-21",
      end_date: "2023-09-24",
      budget: 1500,
    },
    {
      id: 9,
      name: "Copenhagen, Denmark",
      description: "A 3-day trip to Copenhagen, Denmark. See the Little Mermaid, visit the Round Tower, and take a walk along the Nyhavn canal.",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqrq8VpS026HPs7bHyhTi4Yt3eh7lJXcjZfw&usqp=CAU",
      start_date: "2023-09-25",
      end_date: "2023-09-27",
      budget: 1000,
    },
    {
      id: 10,
      name: "Stockholm, Sweden",
      description: "A 4-day trip to Stockholm, Sweden. See the Royal Palace, visit the Vasa Museum, and take a boat ride through the Stockholm archipelago.",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqrq8VpS026HPs7bHyhTi4Yt3eh7lJXcjZfw&usqp=CAU",
      start_date: "2023-09-28",
      end_date: "2023-10-01",
      budget: 1200,
    },
    {
      id: 11,
      name: "Oslo, Norway",
      description: "A 5-day trip to Oslo, Norway. See the Oslo Opera House, visit the Viking Ship Museum, and take a hike in the Holmenkollen ski jump.",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqrq8VpS026HPs7bHyhTi4Yt3eh7lJXcjZfw&usqp=CAU",
      start_date: "2023-10-02",
      end_date: "2023-10-06",
      budget: 1500,
    },
    {
      id: 12,
      name: "Reykjavík, Iceland",
      description: "A 3-day trip to Reykjavík, Iceland. See the Blue Lagoon, visit the Hallgrímskirkja church, and take a walk along the Reykjavík waterfront.",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqrq8VpS026HPs7bHyhTi4Yt3eh7lJXcjZfw&usqp=CAU",
      start_date: "2023-10-07",
      end_date: "2023-10-09",
      budget: 1000,
    },
  ];

  export default data;